### PR TITLE
Refactor to make TC target JDK 7

### PR DESCRIPTION
**Pull request by gusohal**

### CODE REVIEW

**Comment by gusohal** [comment]
I'll do a rebase and resubmit this later today

**Comment by rnorth** [comment]
It's OK - I've done it!

**Comment by gusohal** [comment]
Cool - wasn't much to it at all

**Comment by rnorth** [comment]
Need to test on a JDK7 environment.

**Comment by gusohal** [comment]
I'd been using the JDK7 version the last 3 days or so.




On Sat, Jun 27, 2015 at 7:27 AM -0700, "Richard North" <notifications@github.com<mailto:notifications@github.com>> wrote:


Need to test on a JDK7 environment.

-

**Pull request closed without merging**
